### ISSUE TITLE
Shared Memory Library for Linux RT - missing from 1.1.0.2

### ISSUE THREAD

**Issue by srsmith99** [LabVIEW-DCAF/SharedMemoryModule#14]
Attempted to build the latest version (1.1.0.2) for some testing we are doing. Library was missing. Using LV 2016.

**Comment by leesecho** [comment]
The dependency is not yet published, but should be soon. I realize this prohibits collaboration in the meantime, but we will work to get it resolved quickly. We will soon be releasing a new version of the library which will add numerous improvements (example: data type support, higher performance, C header file generation, etc.).

**Comment by srsmith99** [comment]
I will be patient. Thanks.

**Comment by leesecho** [comment]
I should point out that although the new module will be a noticeable improvement (clear API, unit tests, etc.), it will break existing LV projects. Would you be interested in being a beta tester for the new module, as we produce stable releases?

**Comment by srsmith99** [comment]
Yes I would be interested, the shared memory is a key component in our implementation of DCAF for the control system we are developing.

**Comment by leesecho** [comment]
Thanks so much. It is exciting to be able to share and collaborate on this project, and we value your help. I am finalizing a new beta version which will should be available by next week.

Just to give you more information on the upcoming release... the changes (from a module integration standpoint) with the new release will be relatively minor, as the overall API and editor for the module will not change much. This is essentially an "under the hood" improvement. Implementing the module may only take a few hours of work.

**Comment by leesecho** [comment]
We are planning to post the DCAF Shared Memory Module Sync beta release on Thursday, 3/2. There will be included documentation and example C code for implementation of semaphore based sync, and C header file generation from the DCAF Standard Editor (for compile in C code). The C header file will contain shared memory configuration information, and file version.

**Comment by srsmith99** [comment]
Sounds good. We will plan on trying it out.

**Comment by srsmith99** [comment]
Tried to build the latest version, 1.1.0.13 but VIPM could not find the files shown. I am using LV 2016.
[SM Missing Deps.pdf](https://github.com/LabVIEW-DCAF/SharedMemoryModule/files/821691/SM.Missing.Deps.pdf)

**Comment by leesecho** [comment]
The missing dependencies will be included as attached files with the beta version release, which should be posted later today, or tomorrow at the latest.

**Comment by srsmith99** [comment]
Sorry, looks like I jumped the gun.

**Comment by leesecho** [comment]
Well, we did have to push the beta release a couple of days. I apologize for the inconvenience.

**Comment by srsmith99** [comment]
No problem downloading and opening the shared memory with the beta release. Thanks!
