### ISSUE TITLE
Beta 1.1.0.112 C header missing input data file

### ISSUE THREAD

**Issue by srsmith99** [LabVIEW-DCAF/SharedMemoryModule#16]
In my shared memory implementation I have defined Boolean and doubles as inputs and outputs for a test:
![sharedmem copy](https://cloud.githubusercontent.com/assets/21267032/23760407/9a869634-04bd-11e7-9ee0-7eec59b8fd10.jpg)

After generating the C header the Boolean input file is missing.
![c hdr input error](https://cloud.githubusercontent.com/assets/21267032/23760489/d24b9f56-04bd-11e7-9341-4eccde58e1cb.jpg)

**Comment by leesecho** [comment]
Just to be sure, I want to make sure you saved the configuration before attempting to generate a C header file? As with the Script Includes VI, I believe this tool may use the saved file.

**Comment by srsmith99** [comment]
Yes, I saved the configuration first and made multiple attempts. Also tried closing LabVIEW and then reopening everything.

**Comment by ryanpoulos** [comment]
That's really strange because we've been generating headers while the sames types as you are trying without any issue. Both types and direction have been present for my header files.

**Comment by leesecho** [comment]
We believe we have identified the issue, which is causing the first line of a DCAF Shared Memory Module configuration to be removed if sync is not enabled. The workaround at this time will be to put a "dummy" first line in the module configuration, for now. We plan to upload a new version of the module by the end of the week.

**Comment by ryanpoulos** [comment]
The issue should be fixed with the next commit.

**Comment by srsmith99** [comment]
For what its worth I did have sync enabled but I will wait till the next commit to check it.

**Comment by ryanpoulos** [comment]
It's not sync being enabled, but publishing the iteration start time. In the sync tab, you are able to check a box which will include the cycle start time in the sync structure. When that channel is present, it becomes the first channel in the internal array. I was removing this element so that it wouldn't get put into one of the data structs, but the logic to not remove this channel was flawed and removed element zero even if this channel wasn't there.

**Comment by ryanpoulos** [comment]
For now, until you get the new code, just check the "include cycle start time" in the Sync tab and it will fix the issue. You don't have to use the elements that get added to the struct.

**Comment by srsmith99** [comment]
I did not have that checked so I will do so. Thanks!

**Comment by srsmith99** [comment]
I created the tags under the standard engine settings using the "Create Timing Report Tags?" check box. When I go back to the shared memory synchronization tab and check "Include cycle start time" I get a pop-up. 

![cycle start time popup](https://cloud.githubusercontent.com/assets/21267032/23770458/1fa606f6-04e1-11e7-858f-13681da36548.jpg)

It appears the code is looking for the tag _stdeng_iterstarttime but this tag is not one of those generated when I check the "Create Timing Report Tags?" check box \in standard engine settings. Here is what I get.

![created timing tags](https://cloud.githubusercontent.com/assets/21267032/23770604/ac984060-04e1-11e7-93dc-a6f39b987e7c.jpg)

If I add the _stdeng_iterstarttime tag manually then I no longer get a popup but the "Include cycle start time" box will not stay checked. We will continue to work on it.

**Comment by leesecho** [comment]
It is my understanding that DCAF Engine execution timing tags (mapped when the 'Create Execution Timing Tags' box is checked) will not be visible in the 'Tags' view like user defined tags. They are present, if enabled, but not displayed (or editable) in the 'Tags' view. These timing tags are added to the C header "struct" definition statements when 'Include cycle start time' is checked, and are left out when it is not.

**Comment by ryanpoulos** [comment]
Ahhh yes, Burt just updated the Standard Engine and changed the name of the checkbox that the pop-up refers to. I need to change that text to the new name.

**Comment by srsmith99** [comment]
Good, thanks! Let me know when I can get the updated vip or what vi to fix and we'll try again.

**Comment by srsmith99** [comment]
_It is my understanding that DCAF Engine execution timing tags (mapped when the 'Create Execution Timing Tags' box is checked) will not be visible in the Tags view like user defined tags. They are present, if enabled, but not displayed (and editable)._

The four tags in the screen shot below are populated (displayed) into the Tags table, and editable when the "Create Timing Report Tags?" box is checked.  The **_stdeng_iterstarttime** tag is not displayed but the software also doesn't think it is present.
![created timing tags](https://cloud.githubusercontent.com/assets/21267032/23800298/d6c4af3e-0579-11e7-86d0-bca90814a18c.jpg)

**Comment by ryanpoulos** [comment]
Lee and I talked about this and we realized that you probably have an older build of the Standard Engine, which doesn't have the new tags added yet. We're pushing our Shared Memory changes later, so we'll also send you a new build of the Standard Engine to install as well. We also changed the Shared Memory package to include the new Engine version as a dependency, so it won't install if the correct version of the engine isn't installed.

**Comment by srsmith99** [comment]
I have Standard Engine 2.3.0.83 installed, which is the latest version in VIPM. I will be out this afternoon so will not be able to update till Mon morning.

**Comment by ryanpoulos** [comment]
We are up to build 103 now, so that would explain the discrepancy. Lee is preparing a new package for you as we speak.

**Comment by leesecho** [comment]
The beta release has been updated (v1.1) with the latest Shared Memory Module package, and adding the pre-release DCAF Standard Engine update.

**Comment by srsmith99** [comment]
I installed the vipc (no change actually) and the Standard Engine no problem. When installing the Shared Memory 1.1.0,118, it is missing a package **national_instruments_lib_pthreads_for_labview_on_linux_rt** >= 1.0.0.5. I have 1.0.0.4 installed. Any issues there?

**Comment by ryanpoulos** [comment]
Yes, you'll need that file. Here you go. All of these should be public soon, so the process will be easier.

[national_instruments_lib_pthreads_for_labview_on_linux_rt-1.0.0.5.zip](https://github.com/LabVIEW-DCAF/SharedMemoryModule/files/834423/national_instruments_lib_pthreads_for_labview_on_linux_rt-1.0.0.5.zip)

**Comment by srsmith99** [comment]
Thanks, no problem - it's all part of the process.

**Comment by leesecho** [comment]
The "Linux IPC and Utilities" (dependencies) package has been updated to include the new pthreads library version (1.0.0.5), and I'll be diligent at keeping the packages up to date.

**Comment by srsmith99** [comment]
Everything loaded fine. C hdr file appears correct now. Thanks!

**Comment by ryanpoulos** [comment]
Thanks! Glad it worked!
